Repository wecode-bootcamp-korea/27-westagram-backend-1-team, pull requests merged in 2021-11, with the labels that each got.

#1 [Add] new project created
  students/kyeongraekim/manage.py
  students/kyeongraekim/westagram/__init__.py
  students/kyeongraekim/westagram/asgi.py
  students/kyeongraekim/westagram/settings.py
  students/kyeongraekim/westagram/urls.py
  students/kyeongraekim/westagram/wsgi.py
Labels: Status: 피어 리뷰 요청, Status: 멘토 리뷰 요청

#2 [강태준] Mission 1: Django 초기 세팅
  students/taejun/.gitignore
  students/taejun/manage.py
  students/taejun/my_settings.py.sample
  students/taejun/requirements.text
  students/taejun/westagram/__init__.py
  students/taejun/westagram/asgi.py
  students/taejun/westagram/settings.py
  students/taejun/westagram/urls.py
  students/taejun/westagram/wsgi.py
Labels: Status: 멘토 리뷰 요청

#3 [제갈창민]: Mission 1: Django 초기 세팅
  students/changmin/.gitignore
  students/changmin/manage.py
  students/changmin/requirements.txt
  students/changmin/westagram/__init__.py
  students/changmin/westagram/asgi.py
  students/changmin/westagram/settings.py
  students/changmin/westagram/urls.py
  students/changmin/westagram/wsgi.py
Labels: Status: 피어 리뷰 요청, Status: 멘토 리뷰 요청

#4 [이태연] Mission1:Django 초기 세팅
  students/taeyeon/westagram/.gitignore
  students/taeyeon/westagram/manage.py
  students/taeyeon/westagram/requirements.txt
  students/taeyeon/westagram/westagram/__init__.py
  students/taeyeon/westagram/westagram/asgi.py
  students/taeyeon/westagram/westagram/settings.py
  students/taeyeon/westagram/westagram/urls.py
  students/taeyeon/westagram/westagram/wsgi.py
Labels: Status: 멘토 리뷰 요청

#5 [박재용] Mission 1 : Django 초기 세팅
  students/jaeyong/.gitignore
  students/jaeyong/manage.py
  students/jaeyong/requirements.txt
  students/jaeyong/westagram/__init__.py
  students/jaeyong/westagram/asgi.py
  students/jaeyong/westagram/settings.py
  students/jaeyong/westagram/urls.py
  students/jaeyong/westagram/wsgi.py
Labels: Status: 피어 리뷰 요청, Status: 멘토 리뷰 요청

#7 [강태준] Mission 2: 모델링
  students/taejun/users/__init__.py
  students/taejun/users/admin.py
  students/taejun/users/apps.py
  students/taejun/users/migrations/0001_initial.py
  students/taejun/users/migrations/__init__.py
  students/taejun/users/models.py
  students/taejun/users/tests.py
  students/taejun/users/urls.py
  students/taejun/users/views.py
  students/taejun/westagram/settings.py
  students/taejun/westagram/urls.py
Labels: Status: 피어 리뷰 요청, Status: 멘토 리뷰 요청

#6 [제갈창민]: Mission 2: 모델링
  students/changmin/users/__init__.py
  students/changmin/users/admin.py
  students/changmin/users/apps.py
  students/changmin/users/migrations/__init__.py
  students/changmin/users/models.py
  students/changmin/users/tests.py
  students/changmin/users/views.py
Labels: Status: 수정 요청

#8 [이태연] Mission 2: 모델링
  students/taeyeon/users/__init__.py
  students/taeyeon/users/admin.py
  students/taeyeon/users/apps.py
  students/taeyeon/users/migrations/__init__.py
  students/taeyeon/users/models.py
  students/taeyeon/users/tests.py
  students/taeyeon/users/views.py
Labels: Status: 멘토 리뷰 요청

#11 [강태준] Mission 3: 회원가입 기능 구현
  students/taejun/users/migrations/0002_auto_20211118_1745.py
  students/taejun/users/migrations/0003_alter_user_mbti.py
  students/taejun/users/migrations/0004_alter_user_gender.py
  students/taejun/users/migrations/0005_alter_user_contact.py
  students/taejun/users/migrations/0006_alter_user_mbti.py
  students/taejun/users/migrations/0007_alter_user_mbti.py
  students/taejun/users/models.py
  students/taejun/users/urls.py
  students/taejun/users/views.py
  students/taejun/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#10 [박재용] Mission 2: 모델링
  students/jaeyong/users/__init__.py
  students/jaeyong/users/admin.py
  students/jaeyong/users/apps.py
  students/jaeyong/users/migrations/__init__.py
  students/jaeyong/users/models.py
  students/jaeyong/users/tests.py
  students/jaeyong/users/views.py
Labels: Status: 멘토 리뷰 요청

#14 [이태연] Mission 3: 회원가입 기능 구현
  students/taeyeon/users/migrations/0001_initial.py
  students/taeyeon/users/urls.py
  students/taeyeon/users/views.py
  students/taeyeon/westagram/settings.py
  students/taeyeon/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#12 [제갈창민] Mission 3: 회원가입 기능 구현
  students/changmin/users/migrations/0001_initial.py
  students/changmin/users/models.py
  students/changmin/users/urls.py
  students/changmin/users/views.py
  students/changmin/westagram/settings.py
  students/changmin/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#15 [박재용] Mission 3: 회원가입 기능 구현
  students/jaeyong/users/migrations/0001_initial.py
  students/jaeyong/users/urls.py
  students/jaeyong/users/views.py
Labels: Status: 멘토 리뷰 요청

#13 [강태준] Mission 4: 로그인 기능 구현
  Icon 
  students/taejun/core/__init__.py
  students/taejun/core/admin.py
  students/taejun/core/apps.py
  students/taejun/core/migrations/__init__.py
  students/taejun/core/models.py
  students/taejun/core/tests.py
  students/taejun/core/validation.py
  students/taejun/core/views.py
  students/taejun/users/urls.py
  students/taejun/users/views.py
  students/taejun/westagram/settings.py
Labels: Status: 멘토 리뷰 요청

#19 [강태준] Mission 5: 회원가입 비밀번호 암호화 적용
  students/taejun/requirements.text
  students/taejun/users/views.py
Labels: Status: 멘토 리뷰 요청

#18 [박재용] Mission 4: 로그인 기능 구현
  students/jaeyong/users/urls.py
  students/jaeyong/users/views.py
  students/jaeyong/westagram/settings.py
  students/jaeyong/westagram/urls.py
Labels: Status: 멘토 리뷰 요청

#20 [강태준] Mission 6: 로그인 JWT 적용
  students/taejun/requirements.text
  students/taejun/users/views.py
Labels: Status: 멘토 리뷰 요청

#17 [이태연] Mission 4: 로그인 기능 구현
  students/taeyeon/users/urls.py
  students/taeyeon/users/validation.py
  students/taeyeon/users/views.py
Labels: Status: 멘토 리뷰 요청

#16 [제갈창민] Mission 4: 로그인 기능 구현
  students/changmin/users/urls.py
  students/changmin/users/validation.py
  students/changmin/users/views.py
Labels: Status: 멘토 리뷰 요청
